### ISSUE TITLE
"All Market Tickers Stream" WebSocket API

### ISSUE THREAD

**Issue by 0xBADDCAFE** [glitch100/BinanceDotNet#100]
## Issue Overview
Does the WebSocket API "All Market Tickers Stream" exists? I check docs but can't find about it.
If exists or alternate API usage, please let me know where to written it in doc.

#### Package Version: ?.?.?
4.5.0 (latest)

#### Repro Steps
(No reproducing)

##### Other Information
Related: https://github.com/glitch100/BinanceDotNet/issues/83

**Comment by tht12837a** [comment]
Yes, it does. Here is the link to the official (?)  docs:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#all-market-tickers-stream

If you scroll down to "All Market Tickers Stream," you will see that calling "!ticker@arr" is what you need.

I have coded it in my own project, using WebSocketSharp and it seems to be working properly. It should be quite straightforward to add it to the BinanceExchange.API.

**Comment by glitch100** [comment]
https://www.nuget.org/packages/BinanceDotNet/4.6.1
