### ISSUE TITLE
Cannot get updates of User Data Stream after a while

### ISSUE THREAD

**Issue by gozakturk** [glitch100/BinanceDotNet#103]
Hello there,

I am connecting to user data stream. The callbacks works fine for some time. I am able to receive trade/order/account updates for both my automated buy/sell orders and the orders I place from other platforms such as web or android. After a while my callbacks are not called anymore. The time varies from one run to another. Sometimes I can not get updates after 20 minutes and sometimes after 400 minutes. I tested the code on 3 different pc at 3 different location and the result does not change.

I am not experienced on c# or network programming so I can not see the problem here :(

In the sample I get 500 kline data with 1 min interval to warm the cache of each symbol. Right after the warmup I create a kline socket to receive the continuous updates for the same symbol. These kline sockets seems to be working fine for a very long time. One thing I find interesting is that if I dont create any kline sockets the user data stream seems to be working as I expect. (I am not %100 percent sure about this because I only tried this once and it happened to work.)

I am using precompiled binaries from NuGet of version 4.6.0 I stripped down my project and the problem is still reproduceable. I think it should be debuggable if you still have the pdbs. The program dont contain trading functionality and it is only fetching data. If you want to test it live, you should place orders from web or one of the mobile platforms.

You can use these arguments to run the sample.  
--runmode=Live --symbols=KEYBTC;VIBBTC;GASBTC;NEOBTC;QKCBTC;FUNBTC

I hope this is a rookie mistake of mine :) 

Thanks in advance.
Gokay

[TraderTestv3.zip](https://github.com/glitch100/BinanceDotNet/files/2181405/TraderTestv3.zip)

**Comment by glitch100** [comment]
https://www.nuget.org/packages/BinanceDotNet/4.6.1
