### ISSUE TITLE
GetAccountInformation - malformed requests are sent to the server

### ISSUE THREAD

**Issue by Andreasp123** [glitch100/BinanceDotNet#104]
## Issue Overview
I have had some issues with sending trades and fetching account information but last day it has been completely impossible to fetch information. 

#### Repro Steps
           this.client = new BinanceClient(new ClientConfiguration()
            {
                ApiKey = apiKey,
                SecretKey = secretKey,

            });

            var info = await client.GetAccountInformation(5000); throws
BinanceExchange.API.Models.Response.Error.BinanceBadRequestException: Malformed requests are                  sent to the server. Please review the request object/string
   vid BinanceExchange.API.APIProcessor.<HandleResponse>d__8`1.MoveNext()

##### Other Information
Other information here

**Comment by Andreasp123** [comment]
It has got to do with my computer. I have no solution yet as I haven't found one but the code works fine on another computer.

**Comment by Andreasp123** [comment]
I ran Fiddler and found out that timestamp was ahead of servertime, msg 1021. I syncronized the clock to time.nist.gov and it works again.

**Comment by proteo5** [comment]
Had the same problem and Andreasp123 solution works for me also.
