### ISSUE TITLE
Changes in Binance REST

### ISSUE THREAD

**Issue by Alx65** [glitch100/BinanceDotNet#105]
## Issue Overview
Hello Jon,
Binance team changed ExchangeInfo. They replace MAX_ALGO_OREDS to MAX_NUM_ALGO_ORDERS and EXCHANGE_MAX_ALGO_OREDS to EXCHANGE_MAX_NUM_ALGO_OREDS. As result - en exception in Json deserialization of BinanceExchange.API.Enums.ExchangeInfoSymbolFilterType.

It's excange report - Unable to deserialize message from: https://api.binance.com/api/v1/exchangeInfo. Exception: Error converting value "MAX_NUM_ALGO_ORDERS" to type 'BinanceExchange.API.Enums.ExchangeInfoSymbolFilterType'. Path 'filterType', line 1, position 805.

#### Repro Steps
- Your steps here...

##### Other Information
Other information here

**Comment by Heroloop** [comment]
Hello Jon,
I have create pull request #107  to solve this issue.
Kindly check it.

**Comment by glitch100** [comment]
Further fix in 4.6.2
