### ISSUE TITLE
Binance API ExchangeInfo() changed again

### ISSUE THREAD

**Issue by Bladerender** [glitch100/BinanceDotNet#110]
## Issue Overview
Crashes

#### Repro Steps
Basically they added one more filter. The same way they added MAX_NUM_ALGO_ORDERS, they added ICEBERG_PARTS. So JSON deserialization doesn't work again.

**Comment by veliyasa** [comment]
with this commit looks working but not. There is a still ICEBERG_PARTS error.
Unable to deserialize message from: https://api.binance.com/api/v1/exchangeInfo. Exception: Error converting value "ICEBERG_PARTS" to type 'BinanceExchange.API.Enums.ExchangeInfoSymbolFilterType'. Path 'filterType', line 1, position 798.

And I assume you forgot to change version number.Still 4.6.2 and nuget publish date is Friday, July 20, 2018

**Comment by dmytro-ielkin** [comment]
Is there going to be a new version on NuGet anytime soon?

**Comment by xucito** [comment]
+1 for merging changes into master and pushing NuGet package

**Comment by Igorus7** [comment]
Is it the same problem or new one?

> One or more errors occurred. (Unable to deserialize message from: https://api.binance.com/api/v1/exchangeInfo. Exception: Error converting value "PERCENT_PRICE" to type 'BinanceExchange.API.Enums.ExchangeInfoSymbolFilterType'. Path 'filterType', line 1, position 690.)

**Comment by xucito** [comment]
@Igorus7  No that is a new issue. I have submitted a issue #128 and also a pull request to fix this issue 
GH-129.

I am currently cloning from ipinko and just making the few changes in my pull request locally.

**Comment by glitch100** [comment]
New release has this.
