### ISSUE TITLE
Working limit order? 

### ISSUE THREAD

**Issue by hockeyadc** [glitch100/BinanceDotNet#124]
## Issue Overview
I can place market orders with no issue. Every time I try to place a limit order I get a malformed request

#### Repro Steps
- Your steps here...

##### Other Information
Other information here

**Comment by vburwitz3** [comment]
Thats not a API issue. It has to do with most likely with the Limit price, that must be formatted according to Binance rules. 

You need to do something like the following:
double limitPrice	=Math.Round(calculatedLimit / undTickSize) * undTickSize;

Check the common documentation for that.

**Comment by hockeyadc** [comment]
That worked, thanks
