### ISSUE TITLE
Wrong type for field Amount in class WithdrawListItem.

### ISSUE THREAD

**Issue by Igorus7** [glitch100/BinanceDotNet#127]
## Issue Overview

/BinanceExchange.API/Models/Response/WithdrawListItem.cs

```
namespace BinanceExchange.API.Models.Response
{
    [DataContract]
    public class WithdrawListItem : IResponse
    {
        [DataMember(Order = 1)]
        public string Id { get; set; }

        [DataMember(Order = 2)]
        public long Amount { get; set; }
```
The type of Amount should be **decimal**, not **long**!

It's related to GetWithdrawHistory().

**Comment by glitch100** [comment]
👍 This is fixed in 4.9.0 https://github.com/glitch100/BinanceDotNet/pull/137
