### ISSUE TITLE
New PERCENT_PRICE ExchangeInfoSymbolFilter type

### ISSUE THREAD

**Issue by xucito** [glitch100/BinanceDotNet#128]
## Issue Overview
There is a new ExchangeInfoSymbol called Percentage_Price that throws a error during deserialization.

#### Repro Steps
GetExchangeInfo() using the currently released API.

##### Other Information
Other information here

**Comment by mrtooshshaker** [comment]
will this change also update the nuget package finally?

**Comment by xucito** [comment]
The owner of the nuget package needs to update the nuget package with the fix.

**Comment by mrtooshshaker** [comment]
all good. sorry i wasnt aware of that. ive made changes locally on my own machine to fix any outstanding crashes in any case. but i'm also going to email binance support, because they should really increase their url version to v2, v3 etc when they change the interface. And email all users who have an API key so we are aware of changes, rather than finding out by our apps crashing :(

**Comment by glitch100** [comment]
Is this still happening? If you could put up a PR that would be great 👍

**Comment by khmurach** [comment]
Yes it's still valid issue

**Comment by khmurach** [comment]
// Assembly: BinanceExchange.API, Version=4.7.0.0, Culture=neutral, PublicKeyToken=null

```
  public enum ExchangeInfoSymbolFilterType
  {
    [EnumMember(Value = "PRICE_FILTER")] PriceFilter,
    [EnumMember(Value = "LOT_SIZE")] LotSize,
    [EnumMember(Value = "MIN_NOTIONAL")] MinNotional,
    [EnumMember(Value = "MAX_NUM_ORDERS")] MaxNumOrders,
    [EnumMember(Value = "MAX_NUM_ALGO_ORDERS")] MaxNumAlgoOrders,
    [EnumMember(Value = "ICEBERG_PARTS")] IcebergParts,
  }

```
There is no "PERCENT_PRICE" value. Could you please merge the PR?

**Comment by glitch100** [comment]
I can and will get it merged today or tomorrow - is that alright? 👍

**Comment by glitch100** [comment]
Done 👍  @khmurach

**Comment by khmurach** [comment]
Now it works fine. Thanks, @glitch100!
