### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by Cooksauce** [glitch100/BinanceDotNet#131]
## Issue Overview
There appears to be a server-syncing issue around 12:00am CST. This code worked earlier in the day. Now Binance returns this error message. "Timestamp for this request was 1000ms ahead of the server's time."

#### Repro Steps
- Create new BinanceClient with only Key, and Secret
- var accountTrades = await binanceClient.GetAccountTrades(new AllTradesRequest() {
                                FromId = 0,
                                Limit = 500,
                                Symbol = symbol,
                            });

*Statement above throws BinanceBadRequestException*

##### Other Information
Error Code: -1021
Error Message: "Timestamp for this request was 1000ms ahead of the server's time."
Local Timezone: CST (UTC-06)

Code was ran in the hours of 11:00pm and 12:00am (local times).

**Comment by glitch100** [comment]
Have you synced with the server?

**Comment by Cooksauce** [comment]
Is there a method to call on the BinanceClient to sync it? I may have missed it.

**Comment by glitch100** [comment]
There is something like specifying the TimsetOffset with the Server time I can't remember off the top of my hesd

**Comment by carlostmsp** [comment]
I'm having the same problem but in the call "GetAccountInformation"

**Comment by vburwitz3** [comment]
The problem should not be just with GetAccountTrades() but all types or requests.

Sync the time of your computer with a NTP time server (in windows right lower corner go into the time/date window and clich change time then go to internet time) .
Sadly that really sucks and I havent found a different solution then often syncing my local machine.

Something like "DefaultReceiveWindow=50000," in new BinanceClient(new ClientConfiguration()) does not help to relax the problem.
Any hints very much apprechiated.

**Comment by hientranvn2014** [comment]
Hi all,

I find the solution for syncing local time with server time as below:

**Comment by glitch100** [comment]
Thanks for making that clear for others @hientranvn2014 . 👍
