### ISSUE TITLE
Console app error in 4.7.0

### ISSUE THREAD

**Issue by X7JAY7X** [glitch100/BinanceDotNet#132]
Hello.  I am trying to run the console app and I am getting the error below.  

I downloaded the source, added my Binance API creds and ran the console app in VS2017 (lastest update) and received the following error:

--------------------------
BinanceExchange API - Tester
--------------------------
Interacting with Binance...
1/15/2019 7:24:39 PM|Fatal|WebSocket.Connect|WebSocketSharp.WebSocketException: An error has occurred during a TLS handshake. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

**Comment by X7JAY7X** [comment]
Disregard.  Please delete.

I took the compiled binary to another computer (on a different network) and it works fine.  The firewall must be blocking it on my original computer.

**Comment by glitch100** [comment]
👍
