### ISSUE TITLE
Reading from individual symbol ticker stream fails

### ISSUE THREAD

**Issue by filippopovic** [glitch100/BinanceDotNet#133]
## Issue Overview
Reading Individual symbol ticker stream fails with exception message

> Newtonsoft.Json.JsonSerializationException: 'Error converting value "3682.92000000" to type 'System.Int64'. Path 'a', line 1, position 213.'

#### Repro Steps
Here is the code to reproduce error.

            var client = new BinanceClient(new ClientConfiguration()
            {
                ApiKey = apiKey,
                SecretKey = secretKey,
                Logger = exampleProgramLogger,
            });

           var socket = new InstanceBinanceWebSocketClient(client);
            var sId = socket.ConnectToIndividualSymbolTickerWebSocket("BTCUSDT", b =>
            {
                System.Console.Clear();
                System.Console.WriteLine($"{JsonConvert.SerializeObject(b, Formatting.Indented)}");
                System.Console.SetWindowPosition(0, 0);
            });

```
##### Other Information
Line of code where exception ocurs.
AbstractBinanceWebSocketClient.cs, line 250
`var data = JsonConvert.DeserializeObject<T>(e.Data);`
it belongs to method
`private Guid CreateBinanceWebSocket<T>(Uri endpoint, BinanceWebSocketMessageHandler<T> messageEventHandler) where T : IWebSocketResponse`

Found out that T is BinanceAggregateTradeData using debugger. Seems like we should have another Models/WebSocket class that will represent ticker stream response, because AggregateTradeData does not conform to json response. Or some other class should be used for T. Can't find how it got this class anyway.

**Comment by glitch100** [comment]
Do you want to put up a PR for this? It looks like one of the types is off
