### ISSUE TITLE
Problems with case insensitive deserialization [BinanceTradeOrderData]

### ISSUE THREAD

**Issue by HA07Z7XE** [glitch100/BinanceDotNet#136]
## Issue Overview
There are errors in the deserialization of `BinanceTradeOrderData` from the user data feed, due to case insensitive deserialization from Json.Net https://github.com/JamesNK/Newtonsoft.Json/issues/815

For example, the following message is deserialized as follows. Errors highlighted in purple.
```JSON
{
    "e": "executionReport",
    "E": 1552602237245,
    "s": "BNBBTC",
    "c": "pc_12cbcdd2ebbe4893a5d5de4ef27b3954",
    "S": "SELL",
    "o": "LIMIT",
    "f": "GTC",
    "q": "0.62000000",
    "p": "0.00487400",
    "P": "0.00000000",
    "F": "0.00000000",
    "g": -1,
    "C": "pc_31471433322c4166a05c58152650c96a",
    "x": "CANCELED",
    "X": "CANCELED",
    "r": "NONE",
    "i": 124465346,
    "l": "0.00000000",
    "z": "0.00000000",
    "L": "0.00000000",
    "n": "0",
    "N": null,
    "T": 1552602237240,
    "t": -1,
    "I": 286808464,
    "w": false,
    "m": false,
    "M": false,
    "O": 1552601178372,
    "Z": "0.00000000",
    "Y": "0.00000000"
}
```
![image](https://user-images.githubusercontent.com/19978855/54396662-ae5a0d80-46ab-11e9-806d-66f3fa97d67f.png)
https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md

I tried fixing this, but it looks like a deeper problem with the JSON.Net deserializer that has yet to be fixed. 

I haven't investigated other socket messages but I expect they may have similar problems.

Any suggestions @glitch100 ? I was unable to think of an easy way to fix.

**Comment by glitch100** [comment]
In the actual JSON payload which fields do they correspond too? We can put an attribute to correctly identify what they should deserialize as  . Further if the type is wrong we can build a custom converter. We have done this for other types

**Comment by HA07Z7XE** [comment]
OrderId corresponds to `i` but is binding to `I`.
Order type corresponds to `o` but is binding to `O`.
I had a brief look at converters, but it seemed to me this was a deeper problem with JSON.Net.

**Comment by glitch100** [comment]
This has a workaround in 4.9.0 👍 
https://github.com/glitch100/BinanceDotNet/pull/137

**Comment by rasmuseeg** [comment]
Does this mean that there is now support for case-sensitive deserialization?

**Comment by glitch100** [comment]
@rasmuseeg yes if it follows the pattern we used here
