### ISSUE TITLE
Get the fill price and quote quantity on a filled order.

### ISSUE THREAD

**Issue by yetkinsari** [glitch100/BinanceDotNet#144]
## Issue Overview
I could not get the fill price on a previous market order i submitted after i queried it because price is always zero on the OrderResponse.

#### Package Version: 4.9.1
Master head revision source code.

#### Repro Steps
Get all your previous orders. Pick a market order that filled before.
Check it's order response. Price is always zero.

##### Other Information
As a work around I added 
```
 [DataMember(Order = 15)]
        [JsonProperty(PropertyName = "cummulativeQuoteQty")]
        public decimal CummulativeQuoteQuantity { get; set; }
```
to the end of OrderResponse class to get my quote coin quantity.
Then i calculated the executed price manually from ExecutedQuantity and CummulativeQuoteQuantity which seem to be correctly returned from the server.

If you approve this, please make a similar change so we can know our executed price and executed quote quantity.

BR

**Comment by glitch100** [comment]
Would you like to make a PR for this?

**Comment by yetkinsari** [comment]
Sure. I will do it today.

**Comment by yetkinsari** [comment]
PR created: https://github.com/glitch100/BinanceDotNet/pull/151
