### ISSUE TITLE
All filters equal price filter on GetexchangeInfo()

### ISSUE THREAD

**Issue by veliyasa** [glitch100/BinanceDotNet#145]
each coin have 6 filters on exchangeinfo but right now all 6 filters are price filter.

Package Version: 4.9.1
<img width="736" alt="Screen Shot 2019-04-20 at 20 44 28" src="https://user-images.githubusercontent.com/10462709/56460618-0f14ee00-63ae-11e9-8e35-70b21ee138c3.png">

**Comment by yetkinsari** [comment]
some symbols' price filters have maxprice and minprice as 0. why is that?

**Comment by glitch100** [comment]
Is this an issue in https://www.nuget.org/packages/BinanceDotNet/4.10.0 ?
