### ISSUE TITLE
Not a WebSocket handshake response error

### ISSUE THREAD

**Issue by l0rdak** [glitch100/BinanceDotNet#147]
## Issue Overview
While establishing websocket connection (ConnectToTradesWebSocketCombined, ConnectToDepthWebSocketCombined) the error is continuously occurred:
WebSocketSharp.WebSocketException: Not a WebSocket handshake response.
in WebSocketSharp.WebSocket.doHandshake()

##### Other Information
It seems to me that this is related to the latest binance system upgrade. Checked this with different computes and IP’s.
At the moment solve this by moving to ExchangeSharp.

**Comment by glitch100** [comment]
If this is still an issue please repopen.
