### ISSUE TITLE
MARKET_LOT_SIZE

### ISSUE THREAD

**Issue by l0rdak** [glitch100/BinanceDotNet#148]
## Issue Overview
New MARKET_LOT_SIZE ExchangeInfoSymbolFilterType

##### Other Information
Add:
ExchangeInfoSymbolFilterMarketLotSize
Changes in:
ExchangeInfoSymbolFilterType
ExchangeInfoSymbolFilterConverter

**Comment by glitch100** [comment]
Would you like to open a PR @l0rdak

**Comment by glitch100** [comment]
Checked this exists
