### ISSUE TITLE
Should OriginalClientOrderId be of type STRING?

### ISSUE THREAD

**Issue by ryanjhardinorders** [glitch100/BinanceDotNet#15]
In trying to make sense of what to do with order IDs when creating orders, I was looking at the docs to see what the difference was between clientOrderId and orderId. I think I stumbled upon something. Per Binance's official API documentation, /api/v3/order shows that the parameter origClientOrderId is of type STRING. However, the QueryOrderRequest class in BinanceDotNet has the OriginalClientOrderId property as type LONG. 

I could be missing something, but see: 
See https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#query-order-user_data
vs 
https://github.com/glitch100/BinanceDotNet/blob/master/BinanceExchange.API/Models/Request/QueryOrderRequest.cs

I'm still confused on the difference between clientOrderId and orderId, but I just wanted to point this possible issue with clientOrderId being of type LONG in BinanceDotNet, but being of type STRING in the official Binance API docs. 

If the newClientOrderId is "automatically generated [by Binance] if not sent" in the request, and if it is of type String (as seen in the provided Response example ("clientOrderId": "6gCrw2kRUAF9CvJDGP16IP") see here -- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade), then this will result in an error because BinanceDotNet is expecting LONG, but Binance's API returns STRING. And I don't think it is possible to convert something like "6gCrw2kRUAF9CvJDGP16IP" into LONG.

**Comment by glitch100** [comment]
This sounds like a valid bug. I will investigate and get into our next release. Thanks @ryanjhardinorders

**Comment by ryanjhardinorders** [comment]
@glitch100 
I browsed a bit more in the code and further contrasted it with Binance's API documentation. Please investigate the validity of this/these bug(/s) existing in each of the identified places I've documented below: 
- BinanceDotNet/BinanceExchange.API/Models/**Request**/
  * CancelOrderRequest.cs
  * QueryOrderRequest.cs
- BinanceDotNet/BinanceExchange.API/Models/**Response**/
  * CancelOrderResponse.cs
  * OrderResponse.cs

---
# Request
## CancelOrderRequest:
**BinanceDotNet** shows
``` csharp
[JsonProperty(PropertyName = "origClientOrderId")]
public long? OriginalClientOrderId { get; set; }

public long? NewClientOrderId { get; set; }
```
Reference: https://github.com/glitch100/BinanceDotNet/blob/master/BinanceExchange.API/Models/Request/CancelOrderRequest.cs

**Binance API** documentation shows these parameters:

Name | Type | Mandatory 
--- | --- | ---
origClientOrderId | STRING | No
newClientOrderId | STRING | No

Reference: 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#cancel-order-trade

---

## QueryOrderRequest:
**BinanceDotNet** shows
``` csharp
[JsonProperty(PropertyName = "origClientOrderId")]
public long OriginalClientOrderId { get; set; }
```
Reference: https://github.com/glitch100/BinanceDotNet/blob/master/BinanceExchange.API/Models/Request/QueryOrderRequest.cs

**Binance API** documentation shows these parameters: 

Name | Type | Mandatory 
--- | --- | ---
origClientOrderId | STRING | No

Reference: 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#query-order-user_data

---
# Response
## CancelOrderResponse:
**BinanceDotNet** shows
``` csharp
[JsonProperty(PropertyName = "origClientOrderId")]
public long OriginalClientOrderId { get; set; }

public long ClientOrderId { get; set; }
```
Reference: https://github.com/glitch100/BinanceDotNet/blob/master/BinanceExchange.API/Models/Response/CancelOrderResponse.cs

**Binance API** documentation includes these STRINGS in the response payload:

``` json
{
  "origClientOrderId": "myOrder1",
  "clientOrderId": "cancelMyOrder1"
}
```
Reference: 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#cancel-order-trade

---

## OrderResponse:
**BinanceDotNet** shows
``` csharp
// The OrderResponse model class is actually missing the properties below 
// See the Binance API response payload for an Order Response
```
Reference: https://github.com/glitch100/BinanceDotNet/blob/master/BinanceExchange.API/Models/Response/OrderResponse.cs

**Binance API** documentation includes these STRINGS in the response payload

``` json
{
"clientOrderId": "myOrder1",
"isWorking": true
}
```
Reference: 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#query-order-user_data

---

**Comment by glitch100** [comment]
Hi Ryan, 

Thanks for the in depth reply. I have resolved this in the prerelease 4.0 refactor and that is due to be merged in soon, but beware it has some breaking changes and is liable to change before full release

**Comment by ryanjhardinorders** [comment]
It's a pleasure, and thank YOU for BinanceDotNet. 

I guess the proper way would have been for me to do a pull request and correct this, and then you do a merge if your agree with the changes?? I'm new to git/github philosophy, c#, and .net core, so I myself am trying to figure all this out. 

I'm curious as to what the breaking changes will entail. Perhaps I could email you if I run into any issues, that is, if you are open to that. 

Seriously, if I turn a profit in the binance/crypto world via use of this c# wrapper, I'll definitely send some monetary bits your way. :)

**Comment by glitch100** [comment]
That would be correct yes - and I welcome all pull requests/issues/feature requests.

And it's great that you are contributing to Open Source repositories if you are new to it so great work 👍 . The breaking changes will be around interface namespaces, and `NLog` being replaced, but in turn it will contain various bug fixes, and backwards compat for earlier versions of the .NET Framework.

As or any issues you have you can raise them here or contact me on twitter or email.

And that's great to hear, may your crypto journey be profitable. I would appreciate if you 'star' the repo if you find it helpful - thanks!

**Comment by glitch100** [comment]
In 4.0.0 release.
