### ISSUE TITLE
Cannot figure out how to place limit or stoploss orders without getting "Malformed request"

### ISSUE THREAD

**Issue by josephnevermind** [glitch100/BinanceDotNet#155]
I have been trying  everything I can think if but I cannot place limit or stoploss orders. It's most likely my syntax since market orders and other calls are working fine.
#### Repro Steps
  var createOrder = await client.CreateOrder(new CreateOrderRequest()
            {
                Price = 11400.00m,
                Quantity = 0.001m,
                Symbol = "BTCUSDT",
                Side = OrderSide.Sell,
                Type = OrderType.Limit
            });

##### Other Information
Someone please help. Show me how a working limit and stoploss order should look.

**Comment by KillerInk** [comment]
yes have same problem.

> Malformed requests are sent to the server. Please review the request object/string Timestamp for this request was 1000ms ahead of the server's time.

**Comment by M4kAttack** [comment]
> yes have same problem.
> 
> > Malformed requests are sent to the server. Please review the request object/string Timestamp for this request was 1000ms ahead of the server's time.

I think your problem is that your system get out of sync whit the binance server. I had this problem earlier and downloaded dimension 4 that syncs my system at regular intervals.
https://download.cnet.com/Dimension-4/3000-2094_4-10039998.html

How ever this is not my problem any more. My issue is what I describe above.

**Comment by KillerInk** [comment]
put a try catch around your stoploss order. normaly it tells you where it fails or what is missing

```
catch (BinanceBadRequestException badRequestException){
                Debug.WriteLine(badRequestException.Message + " " + badRequestException.ErrorDetails.Message);}
```

simple time fix
```
var time = await bclient.GetServerTime();
var now = DateTime.UtcNow;
bclient.TimestampOffset = new TimeSpan(time.ServerTime.Hour - now.Hour, time.ServerTime.Minute - now.Minute, time.ServerTime.Second - now.Second);
```

**Comment by glitch100** [comment]
This doesn't look like an issue and more usage? Please reopen if you think differently
