### ISSUE TITLE
add Exchange Information endpoint

### ISSUE THREAD

**Issue by ryanjhardinorders** [glitch100/BinanceDotNet#18]
The official Binance API documentation has an endpoint where **Exchange Information** can be obtained. 
I seriously think this endpoint should be added to the Road to 4.0. 

Reason: Not only does it list Binance's rate limits for using their API, it also provides a contract that developers can use to obtain the most current symbol information -- information that is necessary in order to accurately calculate and make trades for a symbol, such as tickSize, min/maxPrice, min/maxQty, stepSize, etc. For example, if tomorrow Binance decides to change the stepSize for a symbol, if a developer is not aware of the change, then it is very possible that a calculated trade that is particular to a specific level of precision will fail if/when Binance changes things on their side. However, trusting and using this endpoint will allow developers to calculate accurate order info, as it will be based on the most current exchange info that Binance has published for all their symbols.

This endpoint is located along with Test/ping and Check Server Time under General endpoints on the official Binance API: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#exchange-information

I didn't see it under General Endpoints on BinanceDotNet, and at least for the reasons above, I do think it is worthy of swift addition: https://github.com/glitch100/BinanceDotNet/blob/master/docs/REST-API.md#general-endpoints

## Exchange information
```
GET /api/v1/exchangeInfo
```

The response payload looks like this: 

``` json
{
  "timezone": "UTC",
  "serverTime": 1508631584636,
  "rateLimits": [{
      "rateLimitType": "REQUESTS",
      "interval": "MINUTE",
      "limit": 1200
    },
    {
      "rateLimitType": "ORDERS",
      "interval": "SECOND",
      "limit": 10
    },
    {
      "rateLimitType": "ORDERS",
      "interval": "DAY",
      "limit": 100000
    }
  ],
  "exchangeFilters": [],
  "symbols": [{
    "symbol": "ETHBTC",
    "status": "TRADING",
    "baseAsset": "ETH",
    "baseAssetPrecision": 8,
    "quoteAsset": "BTC",
    "quotePrecision": 8,
    "orderTypes": ["LIMIT", "MARKET"],
    "icebergAllowed": false,
    "filters": [{
      "filterType": "PRICE_FILTER",
      "minPrice": "0.00000100",
      "maxPrice": "100000.00000000",
      "tickSize": "0.00000100"
    }, {
      "filterType": "LOT_SIZE",
      "minQty": "0.00100000",
      "maxQty": "100000.00000000",
      "stepSize": "0.00100000"
    }, {
      "filterType": "MIN_NOTIONAL",
      "minNotional": "0.00100000"
    }]
  }]
}
```

Keep up the good work. This wrapper is shaping up nicely.

**Comment by BjornNordblom** [comment]
Just a heads up I'm giving this a shot.

**Comment by glitch100** [comment]
Covered in #24 - closing for that PR to proceed - expecting release in 4.x.x

**Comment by xippix1** [comment]
Is the ticksize implemented already? It's a headache trying to submit orders and having to guess the number of decimals allowed.
