### ISSUE TITLE
Allow (string symbol) in IBinanceClient.GetSymbolOrderBookTicker, and typos in the docs

### ISSUE THREAD

**Issue by ryanjhardinorders** [glitch100/BinanceDotNet#21]
Two issues related to wrapping Binance's "Symbol order book ticker" endpoint:
```GET /api/v3/ticker/bookTicker```

1. BinanceDotNet documentation has errors.   
2. IBinanceClient.GetSymbolOrderBookTicker() should also allow including `(string symbol)` as a parameter. 

### 1. BinanceDotNet documentation: 
- GetSymbolsPriceTicker:List\<SymbolPriceResponse\> is listed twice in the BinanceDotNet docs, and I think the second listing should actually be "GetSymbolOrderBookTicker". Reference: https://github.com/glitch100/BinanceDotNet/blob/master/docs/REST-API.md#getsymbolspricetickerlistsymbolpriceresponse

- This second listing (which should be for GetSymbolOrderBookTicker) is described as providing the "Latest price for all symbols." but if it is to be consistent with Binance's API, it should state "Best price/qty on the order book for a symbol or symbols." Reference: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#symbol-order-book-ticker

### 2. `(string symbol)` parameter in IBinanceClient.GetSymbolOrderBookTicker()
Binance's `GET /api/v3/ticker/bookTicker` endpoint allows providing the optional parameter `symbol` of type STRING, which will return the bookTickers for that particular symbol. Additionally, "If the symbol is not sent, bookTickers for all symbols will be returned in an array." `IBinanceClient.GetSymbolOrderBookTicker()` does not allow one to provide a symbol for obtaining bookTickers for a particular symbol and only returns bookTickers for all symbols. 

Because speed and being lightweight is important, correcting this should be on the roadmap. 

Personally, the extra milliseconds it takes to download the entire list of bookTickers for all symbols is having a negative effect on my app; it is being developed to place an order _immediately after_ a particular calculation is made and before an opportunity is lost, so speed is vital here, and I only need to receive the bookTickers for a particular symbol. Allowing IBinanceClient.GetSymbolOrderBookTicker()'s response to be lightweight for a particular symbol would really help. 

Reference: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#symbol-order-book-ticker

**Comment by glitch100** [comment]
These are valid comments, especially around documentation. You are welcome to raise a PR for those. I can't believe I missed that second point in regards to a specific symbol for a ticket. Again a PR can be raised for this or it can go into the release following 4.0.0
