### ISSUE TITLE
ConnectToTradesWebSocket?

### ISSUE THREAD

**Issue by smabbutt** [glitch100/BinanceDotNet#28]
## Issue Overview
No output from `ConnectToTradesWebSocket` sample code

#### Repro Steps
Sample websocket code like
```
using (var binanceWebSocketClient = new DisposableBinanceWebSocketClient(client))
{
    binanceWebSocketClient.ConnectToDepthWebSocket("ETHBTC", data =>
    {
        System.Console.WriteLine($"DepthCall: {JsonConvert.SerializeObject(data)}");
    });

    Thread.Sleep(180000);
}
```
Gives the expected JSON output with `ConnectToDepthWebSocket` and `ConnectToKlineWebSocket` but 
no output, or exceptions, with `ConnectToTradesWebSocket` using ETHBTC or any of the other pairs I tried. Apologies in advance if I've missed something obvious.
##### Other Information
Using VS2017 latest preview, target framework `netcoreapp2.0`

BinanceDotNet is a cut above the other exchange APIs I've worked with -- thanks! (And check your eth wallet for a small contribution)

**Comment by glitch100** [comment]
Hi @smabbutt ,

Thanks for taking the time to raise the issue; I ran the same code quickly and I do get a response:
![image](https://user-images.githubusercontent.com/1757590/35357135-7b04aed8-014a-11e8-9a9b-9385083a2b7c.png)

Unsure as to what you could be doing wrong:
- Are you providing valid API Keys?
- Are your keys setup with the 'Read Info' flag?

Also thanks again for the contribution it is greatly appreciated; happy to help, and glad you like the library

**Comment by glitch100** [comment]
Seeing as we can't repro and a week has passed I am closing this issue. If you continue to find problems please reopen 👍

**Comment by Implx** [comment]
I confirm that the issue exists. ConnectToTradesWebSocket retuns no ouptput and no exceptions

**Comment by Implx** [comment]
I found a typo in @agrTrades, fixed to @agrTrade (without s) and problem is gone

![image](https://user-images.githubusercontent.com/30937329/35738927-31a32870-0841-11e8-99bd-cd777d5d4619.png)

**Comment by glitch100** [comment]
Are you confirming the issue exists on the `ConnectToTradesWebSocket`?  As the original code sample was just `ConnectToDepthWebSocket`. Do you want to raise a PR for it or shall I?

**Comment by smabbutt** [comment]
Thanks Vadim: sharp-eyed bit of code reading.

Jon, the problem was with `ConnectToTradesWebSocket` only . From my original issue msg:
> Gives the expected JSON output with `ConnectToDepthWebSocket` and `ConnectToKlineWebSocket` but
> no output, or exceptions, with `ConnectToTradesWebSocket`   
  
Glad that's been resolved!

**Comment by glitch100** [comment]
This should be resolved in:
https://www.nuget.org/packages/BinanceDotNet/4.2.1
