### ISSUE TITLE
Can't convert JSON result from string to integer

### ISSUE THREAD

**Issue by parcok** [glitch100/BinanceDotNet#30]
## Issue Overview
Serializer can't convert to integer from string

#### Repro Steps
 private async void button1_Click(object sender, EventArgs e) {
            List<AccountTradeReponse> trades = await client.GetAccountTrades(new AllTradesRequest() {
                Symbol = "XLMETH",
            });
        }

##### Other Information
BinanceExchange.API.Models.Response.Error.BinanceException: 'Unable to deserialize message from: https://www.binance.com/api/v3/myTrades?symbol=XLMETH. Exception: Could not convert string to integer: 60.00000000. Path '[0].qty', line 1, position 73.'
![screenshot](https://user-images.githubusercontent.com/20519128/35484730-23d26df0-0422-11e8-8502-56faeb1b1240.PNG)

**Comment by glitch100** [comment]
Perfect issue - thanks for raising in correct format,  I will get on this soon

**Comment by glitch100** [comment]
Please try the above PR and install that version to test if you are issue is fixed

**Comment by parcok** [comment]
Yes the issue is fixed in my case, thank you very much.
