### ISSUE TITLE
Wrong BinanceAggregateTradeData properties deserialization

### ISSUE THREAD

**Issue by Implx** [glitch100/BinanceDotNet#37]
## Issue Overview

WasBuyerMaker was always false

![image](https://user-images.githubusercontent.com/30937329/35765566-805687fa-08d7-11e8-9a1d-42d92480ee0d.png)

**Comment by glitch100** [comment]
This should be resolved in: https://www.nuget.org/packages/BinanceDotNet/4.2.1
