### ISSUE TITLE
Handling web socket errors

### ISSUE THREAD

**Issue by trydis** [glitch100/BinanceDotNet#38]
## Issue Overview
When looking at the code I'm wondering how to best handle web socket errors?

[Here](https://github.com/glitch100/BinanceDotNet/blob/master/BinanceExchange.API/Websockets/AbstractBinanceWebSocketClient.cs#L178) it throws an exception when a web socket error occurs. 

If i'm not mistaking it will catch it [here](https://github.com/sta/websocket-sharp/blob/master/websocket-sharp/WebSocket.cs#L1418) and log it without the library user being able to catch it?

If so, i guess the only way is to periodically compare `ActiveWebSockets` and `AllSockets`?

**Comment by glitch100** [comment]
Hi @trydis ,

We could add a callback in for errors if you would like, if they are getting swallowed by the underlying library?

**Comment by trydis** [comment]
I think that makes sense, especially since a connection is only valid for 24 hours.

> A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark

**Comment by glitch100** [comment]
Is this still required?

**Comment by trydis** [comment]
No, not by me at least.
