### ISSUE TITLE
GetCompressedAggregateTrades() does not allow absence of optional parameters

### ISSUE THREAD

**Issue by BenLussier** [glitch100/BinanceDotNet#39]
## Issue Overview
The Binance AggTrades REST API only requires symbol parameter to execute. However, if .StartTime is not set in GetCompressedAggregateTradeRequest Model, it defaults to datetime.minvalue which API Guards against and throws exception.

#### Repro Steps
Sorry, working in VB.Net......

Code:
Dim Config As New Client.ClientConfiguration
        Config.ApiKey = "X"
        Config.SecretKey = "C"
        Dim Client As New Client.BinanceClient(Config)
        Dim Req As New Models.Request.GetCompressedAggregateTradesRequest
        Req.Symbol = "LTCBTC"
        Dim Result As List(Of Models.Response.CompressedAggregateTradeResponse) = Await Client.GetCompressedAggregateTrades(Req)

Throws the exception:
"The Guarded argument was DateTime min."

Underlying issue:
Because StartTime and EndTime are not defined as nullable in GetCompressedAggregateTradeRequest Model, they initialize to DateTime.MinValue and thus fail Guard.AgainstDateTimeMin()
This also inherently makes StartTime and EndTime required parameters to GetCompressedAggregateTrades() even though Binance REST API does not require them.

##### Other Information
From Binance API Docs:
![aggtrades](https://user-images.githubusercontent.com/36182391/35843351-d1fa4d1e-0ac4-11e8-874c-145bf47cece8.PNG)
From BinanceDotNet Source:
![guardmindatetime](https://user-images.githubusercontent.com/36182391/35843192-06267f82-0ac4-11e8-8390-8bac97c15f82.PNG)

**Comment by glitch100** [comment]
This should be resolved in:
https://www.nuget.org/packages/BinanceDotNet/4.2.1

**Comment by BenLussier** [comment]
Thank you for responding so fast!! Unfortunately, it looks like you made the change in the websocket only. I am using the client in this particular case.

**Comment by glitch100** [comment]
I think this was fixed? Unless I misunderstand. Please recomment if you are experiencing it
