### ISSUE TITLE
Support for combined streams

### ISSUE THREAD

**Issue by mehtadone** [glitch100/BinanceDotNet#41]
## Issue Overview
Is there support for combined websocket streams? From what it looks  like, it doesnt seem supported yet but happy to be corrected. If this  is the case, is it in the roadmap?

**Comment by glitch100** [comment]
If the official API supports it then we ca support it. Otherwise it's something that I imagine would be supported at the Client level as opposed to on the API wrapper. If there is enough demand we can explore doing it?

**Comment by BZ-CO** [comment]
Hello.Yes, the official API supports it.On the combined streams endpoint, there is Partial Book Depth Streams also.It would be great if you add that too.

**Comment by glitch100** [comment]
https://github.com/glitch100/BinanceDotNet/pull/46 Is working on this. @BZ-CO  - how is it going?
