### ISSUE TITLE
GetCurrentOpenOrders cannot be called without symbol parameter

### ISSUE THREAD

**Issue by clarity99** [glitch100/BinanceDotNet#42]
## Issue Overview
According to API documentation GetCurrentOpenOrders should have Symbol parameter as optional. This api throws the exception if it is null. If I put in "" then Binance says that there is a malformed request. 

#### Repro Steps
 var orders = await client.GetCurrentOpenOrders(new BinanceExchange.API.Models.Request.CurrentOpenOrdersRequest(){ Symbol="" });

 var orders = await client.GetCurrentOpenOrders(new BinanceExchange.API.Models.Request.CurrentOpenOrdersRequest());

##### Other Information
How can one get all currently open orders for the account?

**Comment by glitch100** [comment]
`4.2.2` should have this feature
https://www.nuget.org/packages/BinanceDotNet/4.2.2
Thanks again
