### ISSUE TITLE
Enhancement: Current Binance system upgrade caused API urls to change

### ISSUE THREAD

**Issue by paolobriones** [glitch100/BinanceDotNet#44]
## Issue Overview
The current system upgrade to the Binance exchange caused a change in webservice endpoint urls from **https://www.binance.com/api** to **https://api.binance.com/api/**. The enhancement is to put these base urls into the web.config/app.config

**Comment by glitch100** [comment]
`4.2.2` Release should solve this

I have stuck with current approach for now as it's unlikely this will change again as it is such a breaking change however will consider a configuration approach as a feature later down the line

https://www.nuget.org/packages/BinanceDotNet/4.2.2
