### ISSUE TITLE
QueryOrder fails to deserialize OrderType on TakeProfitLimit

### ISSUE THREAD

**Issue by wallace1981** [glitch100/BinanceDotNet#47]
When we querying order of type "TakeProfitLimit" it fails with exception:

Newtonsoft.Json.JsonSerializationException: Error converting value "TAKE_PROFIT_LIMIT" to type 'BinanceExchange.API.Enums.OrderType'. Path 'type', line 1, position 213. ---> System.ArgumentException: Requested value 'TAKE_PROFIT_LIMIT' was not found.
 
My fix on this is:

    [JsonConverter(typeof(StringEnumConverter))] // Added this attribute.
    public enum OrderType

**Comment by glitch100** [comment]
https://www.nuget.org/packages/BinanceDotNet/4.2.3 should fix this
