### ISSUE TITLE
CreateOrder always Faults

### ISSUE THREAD

**Issue by th3d00d** [glitch100/BinanceDotNet#48]
Whenever I try putting out an Order, it gives be "Order Faulted" back, I can't seem to find any reason for that, or a way to fix it tho.

I am using BinanceDotNet version 4.2.2 (just updated), I started on version 4.0.1, had the same Issue there.

With this code I just try to buy 1 BNB, for example, using USDT - unless I screwed something up there you might can show me, I have no idea what to do... - I got enought USDT on my binance account and all other calls I tried seemed to work just fine (getting the balance, time, stuff like that) - I am just not able to actually create Orders.

```
var createOrder = client.CreateOrder(new CreateOrderRequest()
                {
                    Price = 0,
                    Quantity = 1m,
                    Symbol = "BNBUSDT",
                    Side = OrderSide.Buy,
                    Type = OrderType.Market
                });
                while (!createOrder.IsCompleted)
                {
                    await Task.Delay(100);
                }

                Console.WriteLine("Status: " + createOrder.Status +
                    "\nCompleted: " + createOrder.IsCompleted +
                    "\nCanceled: " + createOrder.IsCanceled +
                    "\nFaulted: " + createOrder.IsFaulted);
```

**Comment by paolobriones** [comment]
You should not set the Price property when you're executing a MARKET BUY Order, BinanceDotNet doesn't correctly evaluate the parameters to CreateOrder() based on the Type of order you are executing.

**Comment by romjab** [comment]
I believe you're trying to buy BNB under the minimum order amount.

The MIN_NOTIONAL filter is one of the few filters your order needs to pass in order to execute.
> MIN_NOTIONAL
> The MIN_NOTIONAL filter defines the minimum notional value allowed for an order on a symbol. An order's notional value is the price * quantity.

source:
`https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md`

**Comment by th3d00d** [comment]
I tried removing the price property, as it seemed logical - but sadly the issue remains. I tried rising the Quantity (i only got enough USDT on my account to buy like 6 BNB right now, so I can't go too far up) to 3m, still told me "faulted" :/

It states, the order did not get canceled, instead it got completed, but is faulted.
![ss 2018-02-21 at 03 19 18](https://user-images.githubusercontent.com/35663940/36484791-aa814c30-171a-11e8-9678-c6db151b1330.png)

**Comment by paolobriones** [comment]
@th3d00d see https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

Scroll down to BNB/USDT, the **Min Order Value** is 10 BNB, moreover, in your original code, you should still remove the **Price** value when executing a MARKET BUY ORDER.

**Comment by paolobriones** [comment]
@th3d00d whilst you're debugging your code, dont use **client.CreateOrder()**, you should be using **client.CreateTestOrder()**. This will send all your parameters to the Binance webservice but doesnt get executed on the exchange. Pretty useful instead of actually buying coins every time you run your code :)

**Comment by th3d00d** [comment]
@paolobriones thanks for that link, I am still a bit confused tho - I did remove the Price value already, I now also use CreateTestOrder and I increased the Quantity so it should definitely be above the limit...

```
var createOrder = client.CreateTestOrder(new CreateOrderRequest()
                {
                    Quantity = 20m,
                    Symbol = "BNBUSDT",
                    Side = OrderSide.Buy,
                    Type = OrderType.Market
                });
```

but for some reason it still stays "Faulted", just like on the screenshot above :/

**Comment by bleblebici** [comment]
@th3d00d could you try to extend the receiveWindow interval of BinanceExchange client? I had a similar issue like you describe and extending receive window to 15000 milliseconds solved my problem. 
Maybe that can solve yours too?

**Comment by th3d00d** [comment]
@bleblebici I feel kinda stupid right now, but I can't figure out where to set the receiveWindow interval, as neither the creation of the client, nor the CreateTestOrder function got a receiveWindow parameter o.O Where do I set this?

**Comment by bleblebici** [comment]
@th3d00d no worries. I realized this issue at the previous versions of BinanceDotNet and receiveWindow can be changed via a parameter when you were calling BinanceClient.CreateOrder method at those times. 

But I suppose @glitch100 changed the interface of BinanceClient while updating the version to 4.x.x and you can't pass receiveWindow parameter via IBinanceClient right now.

To re-enable that feature, I can suggest, please download the source code instead of nuget package and change the CreateOrder method of BinanceClient.cs as


`public async Task<BaseCreateOrderResponse> CreateOrder(CreateOrderRequest request, int receiveWindow = 5000)
        {
            Guard.AgainstNull(request.Symbol);
            Guard.AgainstNull(request.Side);
            Guard.AgainstNull(request.Type);
            Guard.AgainstNull(request.Quantity);

            switch (request.NewOrderResponseType)
            {
                case NewOrderResponseType.Acknowledge:
                    return await _apiProcessor.ProcessPostRequest<AcknowledgeCreateOrderResponse>(Endpoints.Account.NewOrder(request), receiveWindow);
                case NewOrderResponseType.Full:
                    return await _apiProcessor.ProcessPostRequest<FullCreateOrderResponse>(Endpoints.Account.NewOrder(request), receiveWindow);
                default:
                    return await _apiProcessor.ProcessPostRequest<ResultCreateOrderResponse>(Endpoints.Account.NewOrder(request), receiveWindow);
            }

        } `
Of course you need to update your CreateOrder signiture of IBinanceClient interface as 
`Task<BaseCreateOrderResponse> CreateOrder(CreateOrderRequest request, int receiveWindow = 5000)`

I'm not sure, but definitely thinking about it would be worth trying.

**Comment by th3d00d** [comment]
@bleblebici I thank you very much - Wanted to try this right now and saw there was a new update for the API to version 4.2.4, so I thought I'd try that first. The Updated fixed my Issues, but if it ever happens again, I'll check out your take on the matter for sure - thanks for the time you invested in helping me :)
