### ISSUE TITLE
New Feature: Add support for FOK

### ISSUE THREAD

**Issue by paolobriones** [glitch100/BinanceDotNet#50]
## New Feature Overview
Reading up on the Binance API documentation, there are several references to Fill-Or-Kill order types. This is currently not support as of BinanceDotNet 4.x. This is especially useful for algorithmic trading robots as this feature would prevent any slippage to occur once the BUY/SELL Order has been calculated by the system.

#### Package Version: 
BinanceDotNet 4.x

**Comment by glitch100** [comment]
Sounds like a valid feature - we can look into adding it, or you are welcome to pick it up or propose a solution

**Comment by glitch100** [comment]
No reply. Closing
