### ISSUE TITLE
WAPI BaseURL contains an extra space

### ISSUE THREAD

**Issue by SjaaLom** [glitch100/BinanceDotNet#58]
## Issue Overview
In the file Endpoints.cs the private static var WAPIBaseUrl contains a superfluous space at the end. This causes the calls to the WAPI (like depositHistory, withdrawHistory, etc) to fail.

#### Repro Steps
- Create a BinanceClient
- Call client.GetDepositHistory(...)

##### Other Information
When you look at the generated endpoint that is passed to APIProcessor.ProcessRequest(...) in the debugger, you see an extra %20 in the url.

**Comment by glitch100** [comment]
Fixed in 4.3.0
