### ISSUE TITLE
Malformed request when creating two instances of  BinanceClient with different configuration

### ISSUE THREAD

**Issue by N4rk0** [glitch100/BinanceDotNet#59]
## Issue Overview
If you create 2 instances of BinanceClient with different ClientConfiguration then the fist instance is affected by the configuration of the second 

#### Package Version: 
NetStandard2.0 consumed by .net framework 4.61

#### Repro Steps
`
           //Initialise the general client client with config
            var client = new BinanceClient(new ClientConfiguration()
            {
                ApiKey = apiKey,
                SecretKey = secretKey,
                Logger = exampleProgramLogger,
            });

            var cli2 = new BinanceClient(new ClientConfiguration()
            {
                ApiKey = "asd",
                SecretKey = "asd", 
            });

            var startTime = new DateTime(2017, 07, 01, 0, 0, 0, DateTimeKind.Utc);
            var candles = cli2.GetKlinesCandlesticks(new GetKlinesCandlesticksRequest
            {
                Symbol = "ADAETH",
                StartTime = startTime,
                Interval = KlineInterval.OneMinute,
                EndTime = DateTime.MaxValue
            }).Result;
            candles = cli2.GetKlinesCandlesticks(new GetKlinesCandlesticksRequest
            {
                Symbol = "ADAETH",
                StartTime = startTime.AddDays(1),
                Interval = KlineInterval.OneMinute,
                EndTime = DateTime.MaxValue
            }).Result;

            System.Console.WriteLine("Interacting with Binance...");
            var wscli = new DisposableBinanceWebSocketClient(client);
            var UserDataSocket = wscli.ConnectToUserDataWebSocket(new UserDataWebSocketMessages()
            {
                AccountUpdateMessageHandler = d => System.Console.WriteLine("asd"),
                OrderUpdateMessageHandler = d => System.Console.WriteLine("asd"),
                TradeUpdateMessageHandler = d => System.Console.WriteLine("asd"),
            }).Result; 
`

##### Other Information
In the provided example it causes the ConnectToUserDataWebSocket to fail.

**Comment by N4rk0** [comment]
Ok... i found why....
RequestClient is static so whenever a new client is instanced RequestClient.SetAPIKey(string key) is called.

Imho the RequestClient should be an instanced object.
Aside from this unpredictable beahaviour described in this post...what if you want to connect to two different accounts in the same application? That would be impossible.

**Comment by glitch100** [comment]
https://github.com/glitch100/BinanceDotNet/pull/73

Can you try this and see if it fixes it?

**Comment by N4rk0** [comment]
I'll try asap.

**Comment by N4rk0** [comment]
Hi, sorry for long delay.  
It still doesn't work. 
This commit fix it https://github.com/N4rk0/BinanceDotNet/commit/635872da3d7188faa90372dacceea29645a6534e

**Comment by glitch100** [comment]
I am removing this as it wasn't a popular issue. The client only supports a single account however if more want this I will make the change
