### ISSUE TITLE
"Malformed requests are sent to the server.." when using GetAccountInformation()

### ISSUE THREAD

**Issue by kimubach** [glitch100/BinanceDotNet#63]
## Issue Overview
I'm getting "Malformed requests are sent to the server.." error when trying to retrieve account information

**Comment by camerontbelt** [comment]
``var accountInformation = await client.GetAccountInformation(3500);``
This worked for me after initializing the client with api key and secret. 
Are you running a deployed app or is this in visual studio during debug?

**Comment by glitch100** [comment]
Added `DefaultReceiveWindow` into `BinanceClient` configuration in 4.4.0. Defaults to 5000ms. Try changing that across the board 👍
