### ISSUE TITLE
Having issue with deployed app

### ISSUE THREAD

**Issue by camerontbelt** [glitch100/BinanceDotNet#64]
## Issue Overview
The app im building works in visual studio, but once deployed through setup.exe after a click once publish, the binancedotnet api fails to connect to my account. Im not sure if theres something missing in my setup or what. I just wanted to see if anyone here had any ideas. 

If any more information is needed let me know. 
* Im using Visual Studio 2017 professional,
* I've experienced this on two different dev machines as well.
 
#### Exception: 
``The type initializer for 'BinanceExchange.API.RequestClient' threw an exception.``

**Comment by glitch100** [comment]
Interesting, I haven't looked into what changes during apps converted for setup. Have you looked into generic issues around type initializers when using `setup.exe` for converted apps?

**Comment by camerontbelt** [comment]
I havent, I honestly dont even know where to look. I've never had an issue when building a tool and using third party nuget packages like this, but it is possible i'm missing something.

**Comment by camerontbelt** [comment]
An update: The deeper exception is due to a missing reference to System.Net.Http, I have not been able to fix this so far so if theres anything anyone can think of that would help please let me know.

**Comment by camerontbelt** [comment]
As I understand it the Binance api requires 4.1.1 but the one that is installed is 4.3.3. Is it possible that the nuget package needs to be updated in order to reference the latest System.net.http dll?

**Comment by camerontbelt** [comment]
**Update**
@glitch100 It ended up being a missing System.Net.Http.dll in the installation folder after using setup.exe. I assume this is a bug with visual studio 2017 so this can be for anyone that runs into the same issue.

**Comment by glitch100** [comment]
Going to close this - thanks for looking into it 👍
