### ISSUE TITLE
Another -2010 insufficient balance

### ISSUE THREAD

**Issue by tevert** [glitch100/BinanceDotNet#69]
## Issue Overview
I'm attempting to send a market buy order to the ETHUSDT market - from the exception, this is the URL that gets fired: `https://api.binance.com/api/v3/order?newOrderRespType=RESULT&symbol=ETHUSDT&side=BUY&type=MARKET&quantity=91.7066800000`

This returns a -2010 insufficient balance exception, and I can't see why...

#### Repro Steps
- Read account balances using `GetAccountInformation`, specifically pull out the USDT balance
- Connect to the websocket for the ETHUSDT ticker and pull a price update message
- Calculate how much ETH to buy:
- - Divide the USDT balance by the price
- - Deduct 0.0015 of itself (0.001 fee rate * 1.5 just to be safe)
- - Cut off the LOT_SIZE
- Send the buy order: 
```
var response = await binanceClient.CreateOrder(new CreateOrderRequest() {
       Symbol = tradingPair,
       Quantity = Math.Round(calculatedQuantity, 10),
       Side = OrderSide.Buy,
       Type = OrderType.Market
});
```

##### Other Information
It should also be noted that I have 35 BNB available in my account, and the toggle button to use BNB for fees is checked. I technically don't think I should have to pre-deduct *anything* to pay for the fees, since I have the BNB balance, but some other issues seem to suggest otherwise. 

Thanks in advance!

**Comment by glitch100** [comment]
I wonder if it's down to the `quantity` field and whether it is the correct type. Can you retrieve your balance and see what it says?

**Comment by tevert** [comment]
My Tether balance was at ~55k, ETH was near 0 (and BNB was 35). My napkin math says it should've worked.

I tried again but multiplied the fee deduction by 10 and it went through. So the other elements of my buy order must be correct, but for some reason it thinks it needs somewhat more fee allowance than it actually uses (or I'm totally misunderstanding the fee structure).  

Just to clarify, my understanding is that Binance will deduct a 0.1% fee from what currency you're paying, right? And I'm assuming it does a quantity check on your order for fee funds *before* it sees you intend to pay fees with BNB (which is kinda dumb, but whatever)?

**Comment by mynk28** [comment]
@tevert , Can you please provide some information how you calculate amount/quantity etc filters based on the binance api rules https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#symbol-filters here?

**Comment by tevert** [comment]
Sure, code is here: https://github.com/tevert/Trader/blob/master/Trader/Exchange/Binance.cs#L117
1. Divide the quantity (in USDT) by the price
2. Subtract the fee (assumed to be 0.1%)
3. Subtract the modulus of the LOT_SIZE (that was giving me a filter error before I had that)
4. Lastly do a Math.Round to forcibly reduce the number of decimal places; that was also confusing the API. 

Because I'm doing a market buy, I'm pretty sure the filters other than LOT_SIZE don't apply here.

**Comment by mynk28** [comment]
Thanks but I'm having issue with min trading limit. Opened help/issue #70 here.
