### ISSUE TITLE
Cancelled -> Canceled in OrderStatus enum

### ISSUE THREAD

**Issue by jmbooth** [glitch100/BinanceDotNet#7]
The spelling of canceled is wrong in the OrderStatus enum which is throwing an exception on line

messageObject = JsonConvert.DeserializeObject<T>(messageJson);

in APIProcessor.HandleResponse()

I'd submit a fix for this but I don't know how on github. Fixing this locally for now.

**Comment by glitch100** [comment]
Thanks for the comment - I will pick this up today hopefully, or tomorrow

**Comment by glitch100** [comment]
@jmbooth  This has been resolved in release number 3.0.1
https://www.nuget.org/packages/BinanceDotNet/3.0.1
Thanks
