### ISSUE TITLE
How to safely place buy order over binance filters

### ISSUE THREAD

**Issue by mynk28** [glitch100/BinanceDotNet#70]
I'm trying to place buy order but getting lot size error. It seems to be rounding and step size issue.

#### Repro Steps
- Let's say I'm trying to buy ZRXBTC with buy price 0.00005924 BTC and the trading limit is 0.001 BTC.
- So, to get amount/quantity using rounding function like this: Math.Round(tradeLimit / buyPrice, 2), it gives 16.88
- It'll throw error: {3: Server error: {"code":-1013,"msg":"Filter failure: LOT_SIZE"}}

- Also if to get total (quantity * buyPrice) = 0.0009999712
- It falls under MinNotional price (i.e 0.00100000)
- So it throws error, {3: Server error: {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}}

What's the best way to resolve this issue?

**Comment by glitch100** [comment]
Can you give me a valid order in that scenario? Is it because of the amount of decimals used?

**Comment by mynk28** [comment]
Exactly what I meant is:

I've set trading limit per order to 0.001 BTC and trying to apply binance filter. After applying filters I'm removing trailing decimals based on step size from api filters. Due to that Qty goes below min notional amount. Can we just get valid qty so it'll be around defined trading limit?

**Comment by glitch100** [comment]
> Can we just get valid qty ..

Can I retrieve that from the API?  You are welcome to raise a PR or provide an area of code that is giving you issue. Otherwise it sounds like the `MIN_NOTATIONAL` is Binance end
