### ISSUE TITLE
Get type of trade

### ISSUE THREAD

**Issue by Saloed123** [glitch100/BinanceDotNet#75]
Hello, how i can get type of trade by ws.

 **Package Version: 4.4.0**
 ```
var guid = ws.ConnectToTradesWebSocket(pair.ToBinancePair(), OnTradesUpdated);
  private static void OnTradesUpdated(BinanceAggregateTradeData data)
        {
            var trade = new Trade()
            {
                Type = Trade.OrderType.Invalid,
                Price = Price.From(data.Price),
                TotalAmount = data.Quantity,
                Time = data.EventTime.ToUnixTime()
            };
            Console.WriteLine(trade.ToString());
        }
```

How i can get Type from BinanceAggregateTradeData. Me intersting Sell\Buy

**Comment by Bladerender** [comment]
I looked through all the possible documentation Binance gave us. But looks like they don't have such a api property propagated. On the one hand it is kind of bad, on the other hand, there is no such a thing for trade as  "buy" or "sell", because if somebody sold, somebody bought it.

**Comment by glitch100** [comment]
👍
