### ISSUE TITLE
Issue with client.GetAccountInformation(3500);

### ISSUE THREAD

**Issue by Esisxnem** [glitch100/BinanceDotNet#76]
Hi all,
I'm new to C# and I'm trying to understand how to use this library for my own purpose. I've managed to acquire pairs prices for several hours and I've wrote them to a file and other things.

I'm having problems with the following line:

accountInformation = await client.GetAccountInformation(3500);

My console application, let say a simplified version of the example in the package, crashes.

However seems that the connection works fine, and the line:

await client.TestConnectivity();

do not give any problems.

Any ideas?

#### Package Version: 4.2.4

**Comment by tevert** [comment]
You're going to need to give more detail than "crashes". What kind of exception do you get, and what does it say?

**Comment by Esisxnem** [comment]
Thanks for replying.
I'm testing my program in debug environment, not release.
I've made a small modification and now it doesn't crash anymore.

                var accountInformation = new AccountInformationResponse();

                // Firing off a request and catching all the different exception types.
                try
                {
                    accountInformation = await client.GetAccountInformation(3500);
                }
                catch (BinanceBadRequestException badRequestException)
                {
                    System.Console.WriteLine("badRequestException");
                    System.Console.ReadLine();
                }
                catch (BinanceServerException serverException)
                {
                    System.Console.WriteLine("serverException");
                    System.Console.ReadLine();
                }
                catch (BinanceTimeoutException timeoutException)
                {
                    System.Console.WriteLine("timeoutException");
                    System.Console.ReadLine();
                }
                catch (BinanceException unknownException)
                {
                    System.Console.WriteLine("unknownException");
                    System.Console.ReadLine();
                }

However now it returns "badRequestException".

I'm using Windows 7 and Visual Studio 2017

**Comment by tevert** [comment]
You're going to want to debug the code to where you catch that exception, and inspect the properties of the exception for more error details. 

Here's some documentation about debugging in Visual Studio - I'd recommend taking your time here and learning it well; it's an essential development technique. 
https://docs.microsoft.com/en-us/visualstudio/debugger/debugger-basics

**Comment by Alpiona** [comment]
Same problem here

2018-05-03 18:05:25,727 ERROR BinanceExchange.API.APIProcessor - Error Message Received:{"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
BinanceExchange.API.Models.Response.Error.BinanceBadRequestException: Malformed requests are sent to the server. Please review the request object/string

**Comment by Alpiona** [comment]
Forget it, I could not fix it
Sometimes work, sometimes dont

**Comment by ddbuy** [comment]
I had this as well (including it sometimes working and sometimes not).

For me doing
`
            ServerTimeResponse serverTime = await binanceClient.GetServerTime();
            double timeDiff = (serverTime.ServerTime - DateTime.Now.ToUniversalTime()).TotalMilliseconds;
            binanceClient.TimestampOffset = new TimeSpan(0,0,0,0,(int)timeDiff);`

 just before the call to the account thingamajig seemed to make a big difference. Donno if that is useful to anyone.

**Comment by glitch100** [comment]
Hasn't been reported since `TimestampOffset` was provided.
