### ISSUE TITLE
Suggestion: IsAlive Method for Websockets

### ISSUE THREAD

**Issue by romjab** [glitch100/BinanceDotNet#77]
It would be nice to have a method such as IsAlive for the websockets which would return a boolean value if the websocket connection is active or inactive.

The main reason for this is so that I could prevent my bot from trading if any of my websocket connections become inactive. (Binance documentation states that websocket connections are disconnected after 24 hours)

**Comment by glitch100** [comment]
Sounds like a good feature, ultimately the behind logic would be a check on the websocket/24 hours passed. You can (for a work around) implement the latter for now or make a PR 👍
