### ISSUE TITLE
Api stop limit price issue and instancewebsocket for firing

### ISSUE THREAD

**Issue by stmart76** [glitch100/BinanceDotNet#8]
For order place, i get an exception saying the stop price is being sent through, i can see it in the object even though i am not creating it. I fixed this temporarily locally.

My main concern is, (I am getting other websocket messages) when i subscribe to user data feeds, I have everything wired up correctly but when I place or cancel an order, nothing is firing. I am debugging locally and onmessage never fires.

**Comment by glitch100** [comment]
Could you provide any repro steps, or some code so I can debug and diagnose?

Thanks

**Comment by glitch100** [comment]
No update for a few months. So gonna close. Feel free to reopen
