### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by misterYA2018** [glitch100/BinanceDotNet#80]
Hello. My code was working? but yesterday I got an error: The request was aborted. Could not create ssl/tls secure channel

**Comment by glitch100** [comment]
Can you give an example of your code?

**Comment by StefanoRaggi** [comment]
I got the same error running this simple code (Windows 10, NET v4.5.2, BinanceDotNet v4.4.0):
``` C#
            var client = new BinanceClient(new ClientConfiguration
            {
                ApiKey = "...",
                SecretKey = "..."
            });
            var result = client.TestConnectivity().Result;
```

Adding this line at the top solved the issue for me:
``` C#
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

**Comment by Bladerender** [comment]
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 works as well. Looks like binance has blocked TLS1.0 security protocol recently. And if you use for your project ,Net 4.0-4.5 for example, it has by default SecurityProtocolType.Tls|SecurityProtocolType.Ssl3. ExampleProgram from this repository has NetCore 2.0 which by default has Tls 1.0 | Tls 1.1 | Tls 1.2 as far as I remember. I was puzzled for an hour as well why suddenly all the versions of my app doesn't work and ExampleProgram is safe and sound ))
