### ISSUE TITLE
24hr Ticker statistics for all symbols in an array pushed every second

### ISSUE THREAD

**Issue by Tonvengo** [glitch100/BinanceDotNet#83]
Hi.
Is there support for 24hr Ticker statistics for all symbols in an array pushed every second?

https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

**Comment by ThePiLocator** [comment]
I was looking for that too, is this supported?

**Comment by glitch100** [comment]
https://www.nuget.org/packages/BinanceDotNet/4.6.1
