### ISSUE TITLE
Error In CreateWithdrawRequest

### ISSUE THREAD

**Issue by Alx65** [glitch100/BinanceDotNet#84]
## Issue Overview
A short description of the issue
Error In CreateWithdrawRequest
#### Package Version: ?.?.?
4.2.4
#### Repro Steps
WR = await BinClient.CreateWithdrawRequest(new WithdrawRequest
{
  Asset = "BTC",
  Address = W_ad,
  Amount = HMS,
});
I got exception (not binance)
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
I checked under debugger that the WithdrawRequest fields has correct values. 
##### Other Information
Other information here

**Comment by glitch100** [comment]
Duplicate:
https://github.com/glitch100/BinanceDotNet/issues/82

**Comment by Alx65** [comment]
Hi Jon,
I'm not sure because #82 get 1022 Binance error response. I got a nonbinance exception.  In my case it looks as a serialization/deserialization problem around binance call.

**Comment by glitch100** [comment]
What is `W_ad` and `HMS`?

**Comment by Alx65** [comment]
Hi Jon,
string W_ad="1PrpcVTF9Z1Ee7QafqimbyzSKhDCerCU5i";
decimal HMS=0.0105m;

**Comment by glitch100** [comment]
Cheers - I will look at this when I get some time  (very busy at the moment) however someone else can investigate if they want

**Comment by Alx65** [comment]
If someone will try to send (it's real wallet address) and got success, I will return him BTC. I promise )

**Comment by Alx65** [comment]
Hello Jon,
I made couple tries. Change address, change count parameters (include/exclude name). No success.
I tried use last 11.0.2 Json lib instead of 10.0.3 that included in package. No success.
In all cases I got the same exception. I think I can't find solution without your help

**Comment by Alx65** [comment]
Hello Jon,
Problem solved after upgrade from 4.2.4 to 4.5.0
