### ISSUE TITLE
Binding client to one local IP+port

### ISSUE THREAD

**Issue by Alx65** [glitch100/BinanceDotNet#85]
## Issue Overview
There is no way to bind a client to a specific address and port if machine is multihomed.

#### Package Version: ?.?.?
4.2.4
#### Repro Steps
I suggest adding IPEndPoint to a client configuration (with null default)  and use it in RequestClient constructor to bind requests to specific local EndPoint and use it in websocket userdatastreams also.

##### Other Information
Other information here

**Comment by glitch100** [comment]
Specifically what do you want the endpoint to be utilised in? Can you give me an example? Is it the `HttpClient`

**Comment by Alx65** [comment]
Hello Jon,
1. Add variable IPEndPoint to ClientConfiguration and store it in new BinanceClient call. 
2. Bind it where you construct RequestClient. If it null (missing in Client config)  nothing happened. If it specified it will be used.
Something like that. It's start of RequestClient.cs
 
`
        private static IPEndPoint LocalIPEndPoint = null;

        public static IPEndPoint BindIPEndPointCallback(ServicePoint servicePoint, IPEndPoint remoteEndPoint, int retryCount)
        {
            return LocalIPEndPoint;
        }
        static HttpClientHandler SetServicePointOptions(HttpClientHandler handler)
        {
            if (LocalIPEndPoint != null)
            {
                var field = handler.GetType().GetField("startRequest", BindingFlags.NonPublic | BindingFlags.Instance);
                var startRequest = (Action<object>)field.GetValue(handler);

                Action<object> newStartRequest = obj =>
                {
                    var webReqField = obj.GetType().GetField("webRequest", BindingFlags.NonPublic | BindingFlags.Instance);
                    var webRequest = webReqField.GetValue(obj) as HttpWebRequest;
                    webRequest.ServicePoint.BindIPEndPointDelegate = new BindIPEndPoint(BindIPEndPointCallback);

                    startRequest(obj); //call original action
                };

                field.SetValue(handler, newStartRequest); //replace original 'startRequest' with the one above
            }
            return handler;
        }
        static RequestClient()
        {
            var httpClientHandler = SetServicePointOptions(new HttpClientHandler
            {
                AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip
            }
            );

`

**Comment by glitch100** [comment]
No more news on this one and user hasn't followed up. Closing for now
