### ISSUE TITLE
Static BinanceClient

### ISSUE THREAD

**Issue by Egorrko** [glitch100/BinanceDotNet#90]
I created a static class called "Binance" with the "Client" field, and when I start the program I do (Secret and Key variables are taken from the file):
`Binance.Client = new BinanceClient (new ClientConfiguration () {ApiKey = Key, SecretKey = Secret});`
And then, when I call `Binance.Client.GetAccountInformation ();`
I get this exception:
![image](https://user-images.githubusercontent.com/22216155/39701752-cf506ea6-521b-11e8-8693-eeba3e13ffb2.png)

Is this my problem or not?

**Package Version: 4.4.0/4.5.0**

**Comment by Alx65** [comment]
`try 
{
 Binance.Client.GetAccountInformation ();
}
catch (BinanceBadRequestException badRequestException)
{
   System.Console.WriteLine(badRequestException.ErrorDetails.Code + " " + badRequestException.ErrorDetails.Message);
   System.Console.WriteLine(badRequestException.ErrorDetails.RequestMessage);
}
`
It'll get specific description of the problem

**Comment by Egorrko** [comment]
`-1021 Timestamp for this request was 1000ms ahead of the server's time.`
Oops..

**Comment by Egorrko** [comment]
Sorry, but i can't fix it.
Anyone help?

**Comment by Alx65** [comment]
Hi,
Time on your computer is not valid (it'a ahead real time more then 1 s) . You might get Binanceclient.ServerTime and compare it with your local time. One (not best) solution - use Binanceclient.TimestampOffset to compensate a difference.

**Comment by N4rk0** [comment]
1.Synchronize your clock.
2. Before calling anything in the code do this
                var time = Client.GetServerTime().Result;
                var delta = time.ServerTime - DateTime.UtcNow; 
                Client.TimestampOffset = time.ServerTime - DateTime.UtcNow;

**Comment by Egorrko** [comment]
@N4rk0 i doing it one time at start my program, and all working, Thanks.
