### ISSUE TITLE
Error Could not create SSL/TLS secure channel while sending the request

### ISSUE THREAD

**Issue by dante1989** [glitch100/BinanceDotNet#93]
## Issue Overview
Message=An error occurred while sending the request.
WebException: The request was aborted: Could not create SSL/TLS secure channel.

#### Repro Steps
When i send request. I got that Error. This is my code: https://drive.google.com/file/d/1CBmqwtIhVyxA6SjdKh6rIo52ZJ1rwbpJ/view?usp=sharing
I have written my API và Secret in my code
Could You help me to fix that error?
##### Other Information
Error:
WebException: The request was aborted: Could not create SSL/TLS secure channel.

**Comment by devWaleed** [comment]
Same error here.

**Comment by mahl** [comment]
Same issue here.
And commenting out ssl3 does not solve my problem.
