### ISSUE TITLE
GetKlinesCandlesticksRequest returns malformed request

### ISSUE THREAD

**Issue by ClaudioFrateG** [glitch100/BinanceDotNet#95]
The below code return a malformed request

```
public class GetKlinesCandlesticksRequest: IRequest
    {
        [DataMember(Order = 1)]
        public string Symbol { get; set; }

        [DataMember(Order = 2)]
        [JsonConverter(typeof(StringEnumConverter))]
        public KlineInterval Interval { get; set; }

        [DataMember(Order = 3)]
        [JsonConverter(typeof(EpochTimeConverter))]
        public DateTime StartTime { get; set; }

        [DataMember(Order = 4)]
        [JsonConverter(typeof(EpochTimeConverter))]
        public DateTime EndTime { get; set; }

        [DataMember(Order = 5)]
        public int Limit { get; set; }

    }
```

the binance api states

Name | Type | Mandatory | Description
-- | -- | -- | --
symbol | STRING | YES |  
interval | ENUM | YES |  
limit | INT | NO | Default 500; max 500.
startTime | LONG | NO |  
endTime | LONG | NO

for this call

`GetKlinesCandlesticks(new BinanceExchange.API.Models.Request.GetKlinesCandlesticksRequest() { Symbol = f_Symbol, Limit = 100, Interval = BinanceExchange.API.Enums.KlineInterval.OneMinute });`

symbol=EOSBTC&interval=1m&startTime=&endTime=&limit=100 which is malformed according to the binance server as it returns

{"code":-1105,"msg":"Parameter 'startTime' was was empty."}

To fix the problem DateTime needs to be made nullable

```
public class GetKlinesCandlesticksRequest: IRequest
    {
        [DataMember(Order = 1)]
        public string Symbol { get; set; }

        [DataMember(Order = 2)]
        [JsonConverter(typeof(StringEnumConverter))]
        public KlineInterval Interval { get; set; }

        [DataMember(Order = 3)]
        [JsonConverter(typeof(EpochTimeConverter))]
        public DateTime? StartTime { get; set; }

        [DataMember(Order = 4)]
        [JsonConverter(typeof(EpochTimeConverter))]
        public DateTime? EndTime { get; set; }

        [DataMember(Order = 5)]
        public int Limit? { get; set; }

    }
```

**Comment by glitch100** [comment]
Hi @ClaudioFrateG ,

Would you like to make this as a pull request?

To do so, just fork, clone, create a branch, and then make a PR against this repo from your for 👍 

To that end anyone c an

**Comment by ClaudioFrateG** [comment]
Should be done. First time I do a PR here, hopefully I havent screwed up anything :)
