### ISSUE TITLE
Enhancement Idea

### ISSUE THREAD

**Issue by batesy67** [glitch100/BinanceDotNet#97]
## Issue Overview
(Not sure if this is the correct place to post, apologies if not)
When placing a market order, it would be nice to be able to set a % of the amount you'd like to buy -- If it exists, I've not been able to find it. Not sure if Binance allow it via rest, but if it does would be great. I know I can calculate it, but with market fluctuations there may be tiny amounts left over. 

I'm not strong enough in c# to be able to do this myself.

#### Package Version: ?.?.?
V.4.5.0

**Comment by glitch100** [comment]
What do you mean %age? Asking for a percentage of total market?
