### ISSUE TITLE
client method to get client-information gives error

### ISSUE THREAD

**Issue by HamidNL** [glitch100/BinanceDotNet#99]
## Issue Overview
The connection to Binance server is established. Also possible to read the order-book and ticker information and a few more functions. But some functions like client-information leads to some exception saying that the format of request is not correct. I double checked it and I found no issue in code. I don't know the reason of this error.

#### Repro Steps
- Your steps here...

##### Other Information
Other information here

**Comment by glitch100** [comment]
Can you provide repro steps?
